steps:
  # 1. Construction de l'image Docker
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/innoradar-app:$COMMIT_SHA', '.']

  # 2. Push de l'image vers le registre
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/innoradar-app:$COMMIT_SHA']

  # 3. Déploiement sur Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'innoradar' # Nom de votre service Cloud Run
      - '--image'
      - 'gcr.io/$PROJECT_ID/innoradar-app:$COMMIT_SHA'
      - '--region'
      - 'europe-west1' # À adapter selon votre zone
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'

images:
  - 'gcr.io/$PROJECT_ID/innoradar-app:$COMMIT_SHA'